[package]
name = "LinkEcho"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glob = "0.3.1"
rfd = "0.14.1"
winsafe = { version = "0.0.21", features = ["shell"] }
crossterm = "0.27.0"
ratatui = "0.27.0"
color-eyre = "0.6.3"
chrono = "0.4.38"
copypasta = "0.10.1"
win-toast-notify = "0.1.5"